# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("Login")
        MainWindow.resize(822, 460)
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(0, 79, 116);\n"
"   border:none;\n"
"   background-color: transparent;\n"
"   background: transparent;\n"
"   padding: 0;\n"
"   margin:0;\n"
"   color:#fff;\n"
"}\n"
"#centralwidget, #mainBodyContent, #AccBtn{\n"
"background-color: #003f5c;\n"

"}\n"
"\n"
"#pushButton{\n"
"background-color: #2fc692 ;\n"
"color: #003f5c;\n"
"border-radius: 10px 10px 10px 10px;\n"
"padding: 3px 5px;\n"
"}\n"
"QLineEdit{\n"
"background-color: transparent;\n"
"color: #ffffff;\n"
"border-radius: 10px ;\n"
"border: 2px solid #2fc692;\n"
"padding: 4px 8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rightPart = QtWidgets.QWidget(parent=self.centralwidget)
        self.rightPart.setObjectName("rightPart")      
        
       

        self.lineEdit = QtWidgets.QLineEdit(parent=self.rightPart)
        self.lineEdit.setGeometry(QtCore.QRect(70, 165, 165, 36))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_1 = QtWidgets.QLineEdit(parent=self.rightPart)
        self.lineEdit_1.setGeometry(QtCore.QRect(70, 210, 165, 36))
        self.lineEdit_1.setObjectName("lineEdit_1")
        
        self.pushButton = QtWidgets.QPushButton(parent=self.rightPart)
        self.pushButton.setGeometry(QtCore.QRect(80, 290, 146, 26))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        
        self.label = QtWidgets.QLabel(parent=self.rightPart)
        self.label.setGeometry(QtCore.QRect(50, -120, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(34)
        font.setBold(True)
        self.label.setStyleSheet("color: #2fc692;")
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_1 = QtWidgets.QLabel(parent=self.rightPart)
        self.label_1.setGeometry(QtCore.QRect(70, 130, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        
        self.label_2 = QtWidgets.QLabel(parent=self.rightPart)
        self.label_2.setGeometry(QtCore.QRect(75, 250, 170, 30))
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(parent=self.rightPart)
        self.label_3.setGeometry(QtCore.QRect(410, 40, 358, 381))
        self.label.setFixedSize(400, 400)  # Set the width and height
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./images/LogoSautage1.png"))
        self.label_3.setObjectName("label_3")

        self.lineEdit.raise_()
        self.lineEdit_1.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.horizontalLayout.addWidget(self.rightPart)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nom d\'utilisateur"))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "Mot de passe"))
        self.pushButton.setText(_translate("MainWindow", "Se Connecter"))
        self.label.setText(_translate("MainWindow", "Bienvenue sur BG Blast!"))
        self.label_1.setText(_translate("MainWindow", "Connectez-vous à votre compte"))
        self.label_2.setText(_translate("MainWindow", "Continuer autant que visiteur?"))
        




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
   

